import Layout from "@/components/Layout";
import PaystackCheckout from "@/components/PaystackCheckout";
import { ArrowDownLeft, ArrowUpRight, CreditCard, Plus, ReceiptText, ShieldCheck, WalletCards } from "lucide-react";
import { useState } from "react";

type Transaction = { reference: string; amount: number; date: string };

const topUpPlan = { name: "Wallet top-up", price: 0, priceDisplay: "Enter an amount", allowCustomAmount: true };

export default function Wallet() {
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [balance, setBalance] = useState(0);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const formatCurrency = (value: number) => `KES ${value.toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  return (
    <Layout>
      <div className="mx-auto max-w-[1400px] pt-2 lg:pt-10">
        <header className="flex flex-col gap-5 border-b border-[#2d1f4e]/75 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-[#a886dd]"><WalletCards size={14} />Billing center</div><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.045em] text-white sm:text-[32px]">Wallet</h1><p className="mt-2 text-sm text-[#a094b8]">Keep credits ready for smooth renewals and instant deployment.</p></div><div className="flex items-center gap-2 text-xs text-[#9f8bb8]"><ShieldCheck size={16} className="text-violet-300" /> Payments protected by Paystack</div></header>
        <section className="mt-7 overflow-hidden rounded-[24px] border border-[#3b2861] bg-[#1a102e] shadow-[0_22px_60px_rgba(0,0,0,0.24)]"><div className="relative p-6 sm:p-8"><div className="pointer-events-none absolute -right-24 -top-24 h-64 w-64 rounded-full bg-violet-600/20 blur-[70px]" /><div className="relative flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-[13px] font-medium text-[#a094b8]"><CreditCard size={16} className="text-[#b481ff]" />Available balance</div><p className="mt-3 text-4xl font-extrabold tracking-[-0.06em] text-white sm:text-[44px]">{formatCurrency(balance)}</p><p className="mt-3 text-xs text-[#8f80a7]">Use funds for renewals, plan upgrades, and capacity add-ons.</p></div><button type="button" onClick={() => setCheckoutOpen(true)} className="gradient-button inline-flex items-center justify-center gap-2 rounded-xl px-5 py-3.5 text-sm font-extrabold text-white"><Plus size={17} />Add Funds</button></div></div><div className="grid border-t border-[#2d1f4e] sm:grid-cols-3"><div className="flex items-center gap-3 border-b border-[#2d1f4e] p-4 sm:border-b-0 sm:border-r"><span className="rounded-lg bg-violet-500/15 p-2 text-violet-300"><ArrowDownLeft size={16} /></span><div><p className="text-[11px] text-[#a094b8]">Added this month</p><p className="mt-0.5 text-sm font-bold text-white">{formatCurrency(transactions.reduce((total, item) => total + item.amount, 0))}</p></div></div><div className="flex items-center gap-3 border-b border-[#2d1f4e] p-4 sm:border-b-0 sm:border-r"><span className="rounded-lg bg-fuchsia-500/15 p-2 text-fuchsia-300"><ArrowUpRight size={16} /></span><div><p className="text-[11px] text-[#a094b8]">Scheduled renewals</p><p className="mt-0.5 text-sm font-bold text-white">KES 0.00</p></div></div><div className="flex items-center gap-3 p-4"><span className="rounded-lg bg-indigo-500/15 p-2 text-indigo-300"><ReceiptText size={16} /></span><div><p className="text-[11px] text-[#a094b8]">Payment methods</p><p className="mt-0.5 text-sm font-bold text-white">Paystack</p></div></div></div></section>
        <section className="mt-8 overflow-hidden rounded-2xl border border-[#2d1f4e] bg-[#1a102e]"><div className="flex items-center justify-between border-b border-[#2d1f4e] px-5 py-4"><div><h2 className="text-sm font-extrabold text-white">Transaction history</h2><p className="mt-1 text-xs text-[#8f80a7]">Your wallet activity is listed here.</p></div><ReceiptText size={19} className="text-[#936cc9]" /></div><div className="overflow-x-auto"><table className="w-full min-w-[580px] text-left text-sm"><thead className="bg-[#110a20] text-[11px] font-bold uppercase tracking-[0.12em] text-[#89779f]"><tr><th className="px-5 py-3.5">Description</th><th className="px-5 py-3.5">Reference</th><th className="px-5 py-3.5">Date</th><th className="px-5 py-3.5 text-right">Amount</th></tr></thead><tbody>{transactions.length === 0 ? <tr><td colSpan={4} className="px-5 py-14 text-center text-sm text-[#87779d]">No transactions yet. Add funds to get started.</td></tr> : transactions.map((transaction) => <tr key={transaction.reference} className="border-t border-[#2d1f4e]/80 text-[#ddd4eb]"><td className="px-5 py-4 font-semibold">Wallet top-up</td><td className="px-5 py-4 text-xs text-[#a094b8]">{transaction.reference}</td><td className="px-5 py-4 text-xs text-[#a094b8]">{transaction.date}</td><td className="px-5 py-4 text-right font-bold text-emerald-300">+ {formatCurrency(transaction.amount)}</td></tr>)}</tbody></table></div></section>
      </div>
      {checkoutOpen && <PaystackCheckout plan={topUpPlan} onClose={() => setCheckoutOpen(false)} onSuccess={(response, amount) => { setBalance((current) => current + amount); setTransactions((current) => [{ reference: response.reference, amount, date: new Date().toLocaleDateString("en-KE", { day: "2-digit", month: "short", year: "numeric" }) }, ...current]); setCheckoutOpen(false); }} />}
    </Layout>
  );
}
